/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cgl_CglKnapsackCover */

#ifndef _Included_cgl_CglKnapsackCover
#define _Included_cgl_CglKnapsackCover
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cgl_CglKnapsackCover
 * Method:    jni_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_cgl_CglKnapsackCover_jni_1new
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
