/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cgl_CglTwomir */

#ifndef _Included_cgl_CglTwomir
#define _Included_cgl_CglTwomir
#ifdef __cplusplus
extern "C" {
#endif
#undef cgl_CglTwomir_TYPE_NORMAL
#define cgl_CglTwomir_TYPE_NORMAL 0L
/*
 * Class:     cgl_CglTwomir
 * Method:    jni_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_cgl_CglTwomir_jni_1new
  (JNIEnv *, jclass);

/*
 * Class:     cgl_CglTwomir
 * Method:    jni_setTwomirType
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_cgl_CglTwomir_jni_1setTwomirType
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
