/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cgl_CglRedSplit */

#ifndef _Included_cgl_CglRedSplit
#define _Included_cgl_CglRedSplit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cgl_CglRedSplit
 * Method:    jni_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_cgl_CglRedSplit_jni_1new
  (JNIEnv *, jclass);

/*
 * Class:     cgl_CglRedSplit
 * Method:    jni_setLimit
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_cgl_CglRedSplit_jni_1setLimit
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
