/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_coin_Worker */

#ifndef _Included_jni_coin_Worker
#define _Included_jni_coin_Worker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_coin_Worker
 * Method:    jni_getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_1coin_Worker_jni_1getVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
