/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cbc_CbcCompareWolf */

#ifndef _Included_cbc_CbcCompareWolf
#define _Included_cbc_CbcCompareWolf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cbc_CbcCompareWolf
 * Method:    jni_setNodeComparison
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_cbc_CbcCompareWolf_jni_1setNodeComparison
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
