/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cgl_CglProbing */

#ifndef _Included_cgl_CglProbing
#define _Included_cgl_CglProbing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cgl_CglProbing
 * Method:    jni_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_cgl_CglProbing_jni_1new
  (JNIEnv *, jclass);

/*
 * Class:     cgl_CglProbing
 * Method:    jni_setMaxElements
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_cgl_CglProbing_jni_1setMaxElements
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     cgl_CglProbing
 * Method:    jni_setMaxElementsRoot
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_cgl_CglProbing_jni_1setMaxElementsRoot
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     cgl_CglProbing
 * Method:    jni_setMaxLook
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_cgl_CglProbing_jni_1setMaxLook
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     cgl_CglProbing
 * Method:    jni_setMaxLookRoot
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_cgl_CglProbing_jni_1setMaxLookRoot
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     cgl_CglProbing
 * Method:    jni_setMaxPass
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_cgl_CglProbing_jni_1setMaxPass
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     cgl_CglProbing
 * Method:    jni_setMaxPassRoot
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_cgl_CglProbing_jni_1setMaxPassRoot
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     cgl_CglProbing
 * Method:    jni_setRowCuts
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_cgl_CglProbing_jni_1setRowCuts
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     cgl_CglProbing
 * Method:    jni_setUsingObjective
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_cgl_CglProbing_jni_1setUsingObjective
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
