/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cgl_CglMixedIntegerRounding2 */

#ifndef _Included_cgl_CglMixedIntegerRounding2
#define _Included_cgl_CglMixedIntegerRounding2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cgl_CglMixedIntegerRounding2
 * Method:    jni_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_cgl_CglMixedIntegerRounding2_jni_1new
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
