/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_coin_OsiClpSolverInterface */

#ifndef _Included_jni_coin_OsiClpSolverInterface
#define _Included_jni_coin_OsiClpSolverInterface
#ifdef __cplusplus
extern "C" {
#endif
#undef jni_coin_OsiClpSolverInterface_OBJ_SENSE_MIN
#define jni_coin_OsiClpSolverInterface_OBJ_SENSE_MIN 1.0
#undef jni_coin_OsiClpSolverInterface_OBJ_SENSE_MAX
#define jni_coin_OsiClpSolverInterface_OBJ_SENSE_MAX -1.0
/*
 * Class:     jni_coin_OsiClpSolverInterface
 * Method:    jni_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jni_1coin_OsiClpSolverInterface_jni_1new
  (JNIEnv *, jclass);

/*
 * Class:     jni_coin_OsiClpSolverInterface
 * Method:    jni_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jni_1coin_OsiClpSolverInterface_jni_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jni_coin_OsiClpSolverInterface
 * Method:    jni_getModelName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_1coin_OsiClpSolverInterface_jni_1getModelName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jni_coin_OsiClpSolverInterface
 * Method:    jni_getNumCols
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jni_1coin_OsiClpSolverInterface_jni_1getNumCols
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jni_coin_OsiClpSolverInterface
 * Method:    jni_getNumRows
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jni_1coin_OsiClpSolverInterface_jni_1getNumRows
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jni_coin_OsiClpSolverInterface
 * Method:    jni_loadFromCoinModel
 * Signature: (JJZ)I
 */
JNIEXPORT jint JNICALL Java_jni_1coin_OsiClpSolverInterface_jni_1loadFromCoinModel
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     jni_coin_OsiClpSolverInterface
 * Method:    jni_releaseClp
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jni_1coin_OsiClpSolverInterface_jni_1releaseClp
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jni_coin_OsiClpSolverInterface
 * Method:    jni_setModelName
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_jni_1coin_OsiClpSolverInterface_jni_1setModelName
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jni_coin_OsiClpSolverInterface
 * Method:    jni_setObjSense
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_jni_1coin_OsiClpSolverInterface_jni_1setObjSense
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     jni_coin_OsiClpSolverInterface
 * Method:    jni_readMps
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jni_1coin_OsiClpSolverInterface_jni_1readMps
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
